### ISSUE TITLE
Missing "pillow" python module for volatility2 docker

### ISSUE THREAD

**Issue by Abyss-W4tcher** [sk4la/volatility3-docker#10]
Hi, I noticed that the "screenshot" module wasn't working since that "PIL" wasn't installed. Is it possible to fix it ? 

Thanks !

**Comment by sk4la** [comment]
It was indeed missing, thanks for the heads up! I haven't used Volatility 2.6 for a while to be honest.

**Comment by sk4la** [comment]
By the way, PIL has been deprecated for a while and has been replaced by [Pillow](https://python-pillow.org/) (although support for Python 2 has stopped starting with Pillow 7). The [newest release](https://github.com/sk4la/volatility3-docker/releases/tag/1.3.3) includes the latest Pillow release that supports Python 2.7.
