### ISSUE TITLE
Include identifier.cache?

### ISSUE THREAD

**Issue by mischw** [sk4la/volatility3-docker#19]
One the first run of volatility 3 it generates a cache file `identifier.cache` in `/home/unprivileged/.cache/volatility3/`. This takes quite some time to generate and yet is only ~1.4MB. Maybe that is something to consider including in the base image?

**Comment by sk4la** [comment]
Would you happen to have a sample `identifier.cache` file?

**Comment by mischw** [comment]
I think it is not really meant to be passed around since it is generated by volatility upon first start and contains absolute paths to the symbols within the compressed symbol files. What I did in the mean time is to overload your docker image and append a `RUN vol3 frameworkinfo.FrameworkInfo` still with the unprivileged user (the cache is per user). This results in the mentioned `/home/unprivileged/.cache/volatility3/identifier.cache`.

I think it makes sense to include the cache when building the image since it has to be regenerated with every update of the symbol files anyway. But by including it in the image it at least saves a lot of time when actually running volatility. Let me know if you need more info.

**Comment by sk4la** [comment]
Good take, thank you for pointing this out! I have just updated the Volatility 3 images, this change should be reflected in the next pull.

**Comment by sk4la** [comment]
Done in 771f7889c74df0efb23bd000524aeed9e21278f5.
