### ISSUE TITLE
Community Plugins missing in volatility 3 image

### ISSUE THREAD

**Issue by mischw** [sk4la/volatility3-docker#20]
The readme [mentions](https://github.com/sk4la/volatility3-docker/blob/4395b6991aee5f2cd7dc2c900cfd5bbf9c37ff78/README.md?plain=1#L19) the inclusion of the community plugins for the volatility 3 docker image but I can't find them. Looking at the Dockerfile I think they are not actually included?

**Comment by sk4la** [comment]
You are absolutely right!

I have just added community plugins for Volatility 3 in the `sk4la/volatility3` and `sk4la/volatility3:edge` images (located in `/usr/local/share/volatility3/plugins`).

Note that some of these plugins are unmaintained and/or are simply links to the author's repository (which I will most likely never include in the images unless the Volatility Foundation adds it in the community repository).

**Comment by sk4la** [comment]
Done in 67017fc26f0a8baf0dfd5b978a3b91e801b01214.

**Comment by mischw** [comment]
Thanks a lot!
I agree, the plugins are not maintained that well but can't hurt to at least include the main repository anyway :)
